### ISSUE TITLE
Create 'validated' field for haiku

### ISSUE THREAD

**Issue by olliwer** [futurice/HaikuBackend#2]
In order to show the haiku's in a live feed, we need to be able to manually validate the haiku's. This is required so that we can remove or invalidate trolls etc. 

We can create an admin console to the website, which fetches all of the haiku's which haven't yet been validated. For this purpose we need the data model to contain a boolean field `validated`, and the API to offer a GET method which returns all (paged) haiku's where validated==false.

**Comment by jubis** [comment]
There'll be a admin functionality for accepting and rejecting in the backend. The value will be saved in the field <code>validated</code>. Additionally there'll be field <code>rejected</code> to get rid of the inappropriate haikus.
